### ISSUE TITLE
windows下安装tomcat

### ISSUE THREAD

**Issue by baohongfei** [BaoHongfei/wiki#10]
系统环境
Windows Server 2008 R2 Enterprise Service Pack 1

**Comment by baohongfei** [comment]
windows配置
```
JAVA_HOME="C:\Program Files\Java\jdk1.8.0_111"
CLASSPATH="%JAVA_HOME%\lib\dt.jar;%JAVA_HOME%\lib\tools.jar"
PATH=";%JAVA_HOME%\bin"
```

**Comment by baohongfei** [comment]
遇到的问题 1
Tomcat 7.0.73 Invalid character found in the request target
```
java.lang.IllegalArgumentException: Invalid character found in the request target. The valid characters are defined in RFC 7230 and RFC 3986
    at org.apache.coyote.http11.InternalInputBuffer.parseRequestLine(InternalInputBuffer.java:189)
    at org.apache.coyote.http11.AbstractHttp11Processor.process(AbstractHttp11Processor.java:1000)
    at org.apache.coyote.AbstractProtocol$AbstractConnectionHandler.process(AbstractProtocol.java:637)
    at org.apache.tomcat.util.net.JIoEndpoint$SocketProcessor.run(JIoEndpoint.java:318)
    at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145)
    at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:615)
    at org.apache.tomcat.util.threads.TaskThread$WrappingRunnable.run(TaskThread.java:61)
    at java.lang.Thread.run(Thread.java:745)
```
解决方法：降低tomcat版本
http://www.jianshu.com/p/1c870461fa41

**Comment by baohongfei** [comment]
遇到的问题 2
自定义的页面报404
一开始不知道哪错了，后面在`localhost.2017-06-23`日志中看到了是系统的java版本过低造成的。
